const betaStepsData = [
  {
    number: "1.png",
    icon: "register.png",
    title: "REGISTER",
    text: "Create an account on the Project Forest website by completing signup and connecting your MetaMask wallet",
    subText: "Register",
    subIcon: "register-click.svg",
    linkAvailable: true,
    link: "https://projectforest.io/login",
    target: "_self",
    bgColor: "bg-[#9ED57F]",
  },
  {
    number: "2.png",
    icon: "download.png",
    title: "DOWNLOAD",
    text: "Get the closed beta app. Click on the button below to download Project Forest’s APK on your phone.",
    subText: "Closed beta APK",
    subIcon: "download-btn.png",
    linkAvailable: true,
    link: "https://projectforest.io/download-game",
    target: "_blank",
    bgColor: "bg-[#EA8EA2]",
  },
  {
    number: "3.png",
    icon: "claim.png",
    title: "CLAIM",
    text: "Claim your activation code by completing a set of tasks on Gleam. Click below to get started.",
    subText: "Gleam Tasks",
    subIcon: "claim-check.png",
    linkAvailable: true,
    link: "https://gleam.io/competitions/DB317-project-forest-closed-beta-invite",
    target: "_blank",
    bgColor: "bg-[#9791E0]",
  },
  {
    number: "4.png",
    icon: "start.png",
    title: "START",
    text: "Use the activation code sent to your email to log into the beta app and start building your own virtual forest.",
    subText: "",
    subIcon: "",
    linkAvailable: false,
    link: "",
    target: "",
    bgColor: "bg-[#6FC6C5]",
  },
];

export const getAllBetaStepsData = () => betaStepsData;