const betaStepsData = [
  {
    number: "1.png",
    icon: "register.png",
    title: "REGISTER",
    text: "Complete registration on Project Forest website and receive your activation code via email.",
    subText: "Create Account",
    subIcon: "register-click.svg",
    linkAvailable: true,
    link: "https://projectforest.io/login",
    target: "_self",
    bgColor: "bg-[#9ED57F]",
  },
  {
    number: "2.png",
    icon: "download.png",
    title: "DOWNLOAD",
    text: "Click on the button below to download the beta app on iOS and Android mobile devices.",
    subText: "Download APK",
    subIcon: "download-btn.png",
    linkAvailable: true,
    link: "https://projectforest.io/download-game",
    target: "_blank",
    bgColor: "bg-[#EA8EA2]",
  },
  {
    number: "3.png",
    icon: "start.png",
    title: "START",
    text: "Log into the app with your registered username and password and enter the activation code you received to start your grow-to-earn journey.",
    subText: "",
    subIcon: "",
    linkAvailable: false,
    link: "",
    target: "",
    bgColor: "bg-[#6FC6C5]",
  },
];

export const getAllBetaStepsData = () => betaStepsData;