const allData = [
  {
    month: "JAN",
    text: "- Idea generation",
    image: "plant-jan",
    bgColor: " bg-[#818935]",
  },
  {
    month: "FEB",
    text: "- Core team formation",
    image: "plant-feb",
    bgColor: " bg-[#909845]",
  },
  {
    month: "MAR",
    text: "- Planning of technical architecture",
    image: "plant-mar",
    bgColor: " bg-[#9AA250]",
  },
  {
    month: "APR",
    text: "- Planning of game mechanics",
    image: "plant-apr",
    bgColor: " bg-[#9FA758]",
  },
  {
    month: "MAY",
    text: "- Ecosystem planning",
    image: "plant-may",
    bgColor: " bg-[#A3AA61]",
  },
  {
    month: "JUN",
    text: "- Strategic partnerships",
    image: "plant-jun",
    bgColor: " bg-[#AEB56C]",
  },
  {
    month: "JUL",
    text: "- Official Launch of Community Channels",
    image: "plant-jul",
    bgColor: " bg-[#B8BF73]",
  },
  {
    month: "AUG",
    text: "- Official Launch of Website",
    text2: "- Official Launch of Litepaper",
    text3: "- Reforestation Partner Announced",
    image: "plant-aug",
    bgColor: " bg-[#BEC67C]",
  },
  {
    month: "SEP",
    text: "- Project Forest Closed Beta ",
    text2: "- Reforestation Target Announced",
    image: "plant-sep",
    bgColor: " bg-[#CED590]",
  },
  {
    month: "OCT",
    text: "- Genesis NFT airdrop event  ",
    text2: "- Project Forest Open Beta",
    text3: "- DAO establishment",
    image: "plant-oct",
    bgColor: " bg-[#CED590]",
  },
  {
    month: "NOV",
    text: "- NFT sales — Phase 1",
    text2: "- IDO/DEX/Swap",
    text3: "- Launch of NFT marketplace",
    text4: "- Project Forest Official Launch",
    image: "plant-nov",
    bgColor: " bg-[#CED590]",
  },
  {
    month: "DEC",
    text: "- NFT sales — Phase 2",
    text2: "- Social Tree Feature",
    text3: "- Reforestation Target Progress",
    image: "plant-dec",
    bgColor: " bg-[#CED590]",
  },
];

export const getAllRoadmapData = () => allData;
