import Head from "next/head";
import FilterOptions from "../../src/components/marketplace/FilterOptions";
import MarketplaceNav from "../../src/components/marketplace/MarketplaceNav";
import Slider from "../../src/components/marketplace/Slider";

const filterAreas = ["Asia", "Africa", "Europe", "America", "Oceania"];
const filterQualities = ["Common", "Uncommon", "Rare", "Epic", "Legendary"];
const filterSeedMint = ["0", "1", "2"];

export default function MarketPlace() {
  return (
    <div>
      <Head>
        <title>Project Forest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <title>Sustainability-Focused Grow to Earn NFTs | Project Forest</title>
        <meta
          name="title"
          content="Sustainability-Focused Grow to Earn NFTs | Project Forest"
        />
        <meta
          name="description"
          content="Project Forest is a collection of sustainability-focused NFTs that let you make a positive impact on the environment through its grow to earn web3 app."
        />
        <meta
          property="og:image"
          content="https://ankots-public-assets.s3.ap-southeast-1.amazonaws.com/project-forest-meta-image.png"
          key="ogimage"
        />

        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://projectforest.io/" />
        <meta
          property="og:title"
          content="Sustainability-Focused Grow to Earn NFTs | Project Forest"
        />
        <meta
          property="og:description"
          content="Project Forest is a collection of sustainability-focused NFTs that let you make a positive impact on the environment through its grow to earn web3 app."
        />

        <meta
          property="twitter:image"
          content="https://ankots-public-assets.s3.ap-southeast-1.amazonaws.com/project-forest-meta-image.png?v1"
        />
        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content="https://projectforest.io/" />
        <meta
          property="twitter:title"
          content="Sustainability-Focused Grow to Earn NFTs | Project Forest"
        />
        <meta
          property="twitter:description"
          content="Project Forest is a collection of sustainability-focused NFTs that let you make a positive impact on the environment through its grow to earn web3 app."
        />

        {/* <script async src="https://www.googletagmanager.com/gtag/js?id=G-XJKS1PTP6Y"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){ dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'G-XJKS1PTP6Y');
</script> */}
      </Head>

      <div id="smooth-wrapper">
        <div id="smooth-content">
          <div className="full-page-bg-img text-black">
            <div className="flex w-full min-h-screen flex-col">
              <MarketplaceNav />
              <main className="flex border-t border-stone-300">
                <div className="w-72 pr-2 border-r border-stone-300">
                  <div className="flex justify-between border-b border-stone-300 items-center py-4 px-2">
                    <h1 className="text-sm">Filters ({"0"})</h1>
                    <button className="text-sm">Clear All</button>
                  </div>
                  <FilterOptions
                    title="SORT"
                    options={
                      <div className="grid grid-cols-3 gap-2 text-gray-400 text-xs">
                        <button className="bg-white rounded-md py-1">
                          Price ⯅
                        </button>
                        <button className="bg-white rounded-md py-1">
                          Quality ⯅
                        </button>
                        <button className="bg-white rounded-md py-1">
                          Score ⯅
                        </button>
                        <button className="bg-white rounded-md py-1">
                          Price ⯆
                        </button>
                        <button className="bg-white rounded-md py-1">
                          Quality ⯆
                        </button>
                        <button className="bg-white rounded-md py-1">
                          Score ⯆
                        </button>
                      </div>
                    }
                  />
                  <FilterOptions
                    title="AREA"
                    options={
                      <div className="grid grid-cols-3 gap-2 text-gray-400 text-xs">
                        {filterAreas.map((area, i) => (
                          <button key={i} className="bg-white rounded-md py-1">
                            {area}
                          </button>
                        ))}
                      </div>
                    }
                  />
                  <FilterOptions
                    title="QUALITY"
                    options={
                      <div className="grid grid-cols-3 gap-2 text-gray-400 text-xs">
                        {filterQualities.map((area, i) => (
                          <button key={i} className="bg-white rounded-md py-1">
                            {area}
                          </button>
                        ))}
                      </div>
                    }
                  />
                  <FilterOptions
                    title="SEEDS MINT"
                    options={
                      <div className="grid grid-cols-3 gap-2 text-gray-400 text-xs">
                        {filterSeedMint.map((area, i) => (
                          <button key={i} className="bg-white rounded-md py-1">
                            {area}
                          </button>
                        ))}
                      </div>
                    }
                  />
                  <FilterOptions
                    title="LEVEL"
                    options={<Slider min={0} max={35} />}
                  />
                  <FilterOptions
                    title="AGE"
                    options={<Slider min={0} max={100} />}
                  />
                </div>
                <div className="flex-grow px-2 pt-2">Market Place</div>
              </main>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
