import Head from "next/head";
import Navbar from "../../src/components/navbar/Navbar";
import Hero from "../../src/components/hero/Hero";
import Footer from "../../src/components/footer/Footer";
import HowItWorks from "../../src/components/how-it-works/HowItWorks";
import MailingList from "../../src/components/mailing-list/MailingList";
import Reforestation from "../../src/components/reforestation/Reforestation";
import NFTSlider from "../../src/components/NFT/NFTSlider";
import Roadmap from "../../src/components/roadmap/Roadmap";
import Token from "../../src/components/token/Token";
import React, { useEffect } from "react";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
// import { ScrollSmoother } from "gsap-trial/dist/ScrollSmoother";
import { ScrollToPlugin } from "gsap/dist/ScrollToPlugin";
import { gsap, Power3 } from "gsap";
import PageGradientTitle from "../../src/components/shared/PageGradientTitle";
import ImageComponent from "../../src/components/shared/ImageComponent";
import Team from "../../src/components/team/Team";

export default function AboutUs() {
  useEffect(() => {
    gsap.registerPlugin(ScrollTrigger);
    gsap.registerPlugin(ScrollToPlugin);

    // let smoother = ScrollSmoother.create({
    //   wrapper: '#smooth-wrapper',
    //   content: '#smooth-content',
    //   smooth: 2,
    //   smoothTouch: 0.1,

    // });

    gsap.fromTo("#home", { opacity: 0 }, { opacity: 1, duration: 1 });
    gsap.fromTo(
      ".how-section",
      {
        opacity: 0,
        y: 500,
      },
      {
        opacity: 1,
        duration: 3,
        ease: Power3.easeInOut,
        y: 0,
        // scrollTrigger: {
        //   trigger: "#how-it",
        //   start: "top top",
        //   end: "bottom center",
        //   scrub: true,
        // }
      }
    );
  }, []);

  return (
    <div>
      <Head>
        <title>Project Forest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <title>Sustainability-Focused Grow to Earn NFTs | Project Forest</title>
        <meta
          name="title"
          content="Sustainability-Focused Grow to Earn NFTs | Project Forest"
        />
        <meta
          name="description"
          content="Project Forest is a collection of sustainability-focused NFTs that let you make a positive impact on the environment through its grow to earn web3 app."
        />
        <meta
          property="og:image"
          content="https://ankots-public-assets.s3.ap-southeast-1.amazonaws.com/project-forest-meta-image.webp"
          key="ogimage"
        />

        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://projectforest.io/" />
        <meta
          property="og:title"
          content="Sustainability-Focused Grow to Earn NFTs | Project Forest"
        />
        <meta
          property="og:description"
          content="Project Forest is a collection of sustainability-focused NFTs that let you make a positive impact on the environment through its grow to earn web3 app."
        />
        <meta
          property="twitter:image"
          content="https://ankots-public-assets.s3.ap-southeast-1.amazonaws.com/project-forest-meta-image.png?v1"
        />
        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content="https://projectforest.io/" />

        <meta
          property="twitter:title"
          content="Sustainability-Focused Grow to Earn NFTs | Project Forest"
        />
        <meta
          property="twitter:description"
          content="Project Forest is a collection of sustainability-focused NFTs that let you make a positive impact on the environment through its grow to earn web3 app."
        />
      </Head>
      <main>
        <div id="smooth-wrapper">
          <div id="smooth-content">
            <div className="full-page-bg-img">
              <Navbar />

              <div className="section-spacing relative">
                <PageGradientTitle title="About Us" className="uppercase" />
                <p className="page-description mt-4">
                  Project Forest was established with a simple but realistic
                  mission: to restore the Earth’s environment. At Project
                  Forest, we all come to work every day because we want to solve
                  the biggest crisis humanity has ever faced. We believe that
                  through Project Forest, we can reforest our planet and achieve
                  sustainability in the broader global environment and resolve
                  the climate crisis whilst incorporating the principles of
                  Web-3 technology amidst the widespread adoption of blockchain
                  technology.
                </p>

                <div className="flex justify-between items-center flex-col-reverse md:flex-row mt-[2rem] md:mt-[5rem] md:gap-[4rem] gap-[2rem] ">
                  <div className="w-full h-[255px] md:w-[40%] md:h-[350px] bg-[#434343] bg-opacity-10 rounded-2xl mt-6 md:mt-0"></div>
                  <div className="flex-1 flex flex-col justify-center md:justify-start items-center md:items-start">
                  <div className="w-full ">
                    <PageGradientTitle
                      title="Mission"
                      className="uppercase"
                    />
                    </div>
                    <p className="page-description mt-4">
                      Project Forest is a Web3 project with an initiative to
                      reforest trees worldwide and improve the environment.
                      Project Forest aims to be the world’s first Grow-to-Earn
                      NFT mobile game that positively impacts the Earth’s
                      environment and be the next-generation NFT project that
                      introduces the concept of De-Fi and Grow-to-Earn to the
                      Web3 space.
                    </p>
                  </div>
                </div>

                <div className="flex justify-between items-center flex-col md:flex-row mt-[2rem] md:mt-[5rem] md:gap-[4rem] gap-[2rem] ">
                  <div className="flex-1 flex flex-col justify-center md:justify-start items-center md:items-start">
                    <div className="w-full ">
                    <PageGradientTitle
                      title="Vision"
                      className="uppercase"
                    />
                    </div>
                    <p className="page-description mt-4">
                      We envision ourselves to be the pioneers that introduce
                      real-world ecological utility to the blockchain revolution
                      by bridging the gap between technology and
                      environmentalism. We see ourselves as the breakthrough to
                      the Web3 space that introduces NFTs with real-world
                      utilities which promote reforestation and provide new and
                      sustainable use cases with a greater utility to the De-Fi
                      space.
                    </p>
                  </div>
                  <div className="w-full h-[255px] md:w-[40%] md:h-[350px] bg-[#434343] bg-opacity-10 rounded-2xl"></div>
                </div>
                <div className="border-dashed h-[10px] border-t-[2px] md:mt-16 mt-12 border-[#434343] border-opacity-10"></div>
                <Team />
              </div>
            </div>

            <Footer />
          </div>
        </div>
      </main>
    </div>
  );
}
