import Head from "next/head";
import Navbar from "../src/components/navbar/Navbar";
import Hero from "../src/components/hero/Hero";
import Footer from "../src/components/footer/Footer";
import HowItWorks from "../src/components/how-it-works/HowItWorks";
import MailingList from "../src/components/mailing-list/MailingList";
import Reforestation from "../src/components/reforestation/Reforestation";
import NFTSlider from "../src/components/NFT/NFTSlider";
import Roadmap from "../src/components/roadmap/Roadmap";
import Token from "../src/components/token/Token";
import Aos from "aos";
import React, { useEffect, useRef } from "react";
import Scrollbar from "smooth-scrollbar";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import {ScrollToPlugin} from "gsap/dist/ScrollToPlugin";
import { gsap, TimelineLite, Power3 } from "gsap";

export default function Home() {
  // var options = {
  //   damping: 0.09,
  // };
  // const Scroll = () => {
  //   useEffect(() => {
  //     Scrollbar.init(document.body, options);
  //   }, []);
  //   return null;
  // };


  useEffect(() => {
    Aos.init({ duration: 1000 });

    gsap.registerPlugin(ScrollTrigger);
    gsap.registerPlugin(ScrollToPlugin);

    gsap.fromTo("#home", {opacity: 0}, {opacity: 1, duration: 1});
    gsap.fromTo(
      ".how-section",
      {
        opacity: 0,
        y: 200
      },
      {
        opacity: 1,
        duration: 3,
        ease: Power3.easeInOut,
        y: 0
        // scrollTrigger: {
        //   trigger: "#how-it",
        //   start: "top top",
        //   end: "bottom center",
        //   scrub: true,
        // }
      } ///TODO fix scrollTrigger to trigger based on ID or ClassName
     
    );
  }, []);




  return (
    <div>
      <Head>
        <title>Project Forest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="scrolling">
        <Navbar />

        {/* Smooth Scroll for the page */}
        {/* <Scroll /> */}

        {/* Hero Section */}
        <Hero />

        {/* <div className="anime-section">  */}
        {/* How It Works Section */}
        <HowItWorks />

        {/* NFT Slider Section */}
        <NFTSlider />

        {/* Token Section */}
        <Token />

        {/* Roadmap Section */}
        <Roadmap />

        {/* Reforestation Section */}
        <Reforestation />

        {/* Newsletter Section */}
        <MailingList />
        <Footer />
        {/* </div> */}
      </main>
    </div>
  );
}